### ISSUE TITLE
System.Exception: Type byte is not Null or String

### ISSUE THREAD

**Issue by Cyl18** [Milkitic/Osu-Player#62]
![image](https://user-images.githubusercontent.com/14993992/99185837-4f557180-2787-11eb-81e2-d4184b3f883d.png)

====================11/15/2020 9:10:32 PM====================
System.Exception: Type byte is not Null or String (position: 34)
   at osu.Shared.Serialization.SerializationReader.ReadString()
   at osu_database_reader.Components.Beatmaps.BeatmapEntry.ReadFromStream(SerializationReader r)
   at osu_database_reader.BinaryFiles.OsuDb.ReadFromStream(SerializationReader r)
   at Milky.OsuPlayer.App.ReadDb() in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\App.xaml.cs:line 288
   at System.Lazy\`1.CreateValue()
   at System.Lazy\`1.LazyInitValue()
   at System.Lazy\`1.get_Value()
   at Milky.OsuPlayer.App.get_Beatmaps() in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\App.xaml.cs:line 40
   at Milky.OsuPlayer.PlayerList.RefreshPlayList(FreshType freshType, Nullable\`1 playListMode, IEnumerable\`1 entries, Boolean finishList) in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\PlayerList.cs:line 46
   at Milky.OsuPlayer.Windows.MainWindow.SetPlayMode(PlayerMode playmode) in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\Windows\MainWindow.Event.cs:line 439
   at Milky.OsuPlayer.Windows.MainWindow.<Window_Loaded>d__49.MoveNext() in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\Windows\MainWindow.Event.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Milky.OsuPlayer.App.Main() in C:\Users\YureruMiira\Source\Repos\完整项目\Osu-Player\OsuPlayer.Wpf\App.xaml.cs:line 69

**Comment by Milkitic** [comment]
这个版本太老了，是数据库都没有更新的版本
先用2.1版，近期将推2.2版。
